"""
TechSupport Hub Bot - Comprehensive Training Data
Extensive training examples covering diverse customer phrasings
"""

# Core training data with MANY variations per intent
CORE_TRAINING_DATA = [
    # ============================================================================
    # GREETING (50+ variations)
    # ============================================================================
    ("hello", "greeting"),
    ("hi", "greeting"),
    ("hey", "greeting"),
    ("hi there", "greeting"),
    ("hello there", "greeting"),
    ("hey there", "greeting"),
    ("good morning", "greeting"),
    ("good afternoon", "greeting"),
    ("good evening", "greeting"),
    ("greetings", "greeting"),
    ("hi bot", "greeting"),
    ("hello bot", "greeting"),
    ("hey bot", "greeting"),
    ("yo", "greeting"),
    ("sup", "greeting"),
    ("whats up", "greeting"),
    ("howdy", "greeting"),
    ("hiya", "greeting"),
    ("hi support", "greeting"),
    ("hello support", "greeting"),
    ("good day", "greeting"),
    ("morning", "greeting"),
    ("afternoon", "greeting"),
    ("evening", "greeting"),
    ("hi i need help", "greeting"),
    ("hello i need assistance", "greeting"),
    ("hey can you help", "greeting"),
    ("hi is anyone there", "greeting"),
    ("hello is this support", "greeting"),
    ("hey support team", "greeting"),
    
    # ============================================================================
    # FAREWELL (40+ variations)
    # ============================================================================
    ("goodbye", "farewell"),
    ("bye", "farewell"),
    ("bye bye", "farewell"),
    ("see you", "farewell"),
    ("see ya", "farewell"),
    ("thanks bye", "farewell"),
    ("thank you goodbye", "farewell"),
    ("ok bye", "farewell"),
    ("alright bye", "farewell"),
    ("have a good day", "farewell"),
    ("have a nice day", "farewell"),
    ("take care", "farewell"),
    ("catch you later", "farewell"),
    ("later", "farewell"),
    ("peace", "farewell"),
    ("im done", "farewell"),
    ("thats all", "farewell"),
    ("nothing else", "farewell"),
    ("no more questions", "farewell"),
    ("all good now", "farewell"),
    ("problem solved thanks", "farewell"),
    ("that helped thanks bye", "farewell"),
    ("appreciate it bye", "farewell"),
    ("thanks for your help goodbye", "farewell"),
    ("ok thanks", "farewell"),
    ("got it thanks", "farewell"),
    ("understood thanks", "farewell"),
    
    # ============================================================================
    # ACCOUNT ACCESS - Login Issues (100+ variations)
    # ============================================================================
    ("cant log in", "account_access"),
    ("can't login", "account_access"),
    ("cannot log in", "account_access"),
    ("unable to login", "account_access"),
    ("login not working", "account_access"),
    ("login problem", "account_access"),
    ("login issue", "account_access"),
    ("cant sign in", "account_access"),
    ("can't signin", "account_access"),
    ("cannot sign in", "account_access"),
    ("unable to sign in", "account_access"),
    ("signin not working", "account_access"),
    ("forgot password", "account_access"),
    ("forgot my password", "account_access"),
    ("dont remember password", "account_access"),
    ("don't remember my password", "account_access"),
    ("lost password", "account_access"),
    ("lost my password", "account_access"),
    ("need to reset password", "account_access"),
    ("reset password", "account_access"),
    ("password reset", "account_access"),
    ("how to reset password", "account_access"),
    ("change password", "account_access"),
    ("forgot username", "account_access"),
    ("forgot my username", "account_access"),
    ("dont remember username", "account_access"),
    ("lost username", "account_access"),
    ("what is my username", "account_access"),
    ("account locked", "account_access"),
    ("my account is locked", "account_access"),
    ("locked out of account", "account_access"),
    ("locked out", "account_access"),
    ("account suspended", "account_access"),
    ("account disabled", "account_access"),
    ("account blocked", "account_access"),
    ("access denied", "account_access"),
    ("login failed", "account_access"),
    ("login keeps failing", "account_access"),
    ("wrong password error", "account_access"),
    ("invalid credentials", "account_access"),
    ("invalid password", "account_access"),
    ("incorrect password", "account_access"),
    ("password not accepted", "account_access"),
    ("password doesnt work", "account_access"),
    ("password not working", "account_access"),
    ("getting login error", "account_access"),
    ("login error message", "account_access"),
    ("error when logging in", "account_access"),
    ("error during login", "account_access"),
    ("cant access my account", "account_access"),
    ("cannot access account", "account_access"),
    ("unable to access account", "account_access"),
    ("no access to account", "account_access"),
    ("authentication failed", "account_access"),
    ("authentication error", "account_access"),
    ("two factor not working", "account_access"),
    ("2fa problem", "account_access"),
    ("two factor authentication issue", "account_access"),
    ("2fa code not working", "account_access"),
    ("verification code not working", "account_access"),
    ("didnt receive verification code", "account_access"),
    ("verification code expired", "account_access"),
    ("too many login attempts", "account_access"),
    ("account temporarily locked", "account_access"),
    ("need to unlock account", "account_access"),
    ("how to unlock my account", "account_access"),
    ("email not recognized", "account_access"),
    ("username not found", "account_access"),
    ("account not found", "account_access"),
    ("user does not exist", "account_access"),
    ("session expired", "account_access"),
    ("keeps logging me out", "account_access"),
    ("automatically logged out", "account_access"),
    ("login keeps timing out", "account_access"),
    
    # ============================================================================
    # TECHNICAL ISSUES - Bugs, Errors, Performance (150+ variations)
    # ============================================================================
    ("app crashing", "technical_issue"),
    ("app crashes", "technical_issue"),
    ("application crashing", "technical_issue"),
    ("keeps crashing", "technical_issue"),
    ("crashes when i open it", "technical_issue"),
    ("crashes on startup", "technical_issue"),
    ("crashes randomly", "technical_issue"),
    ("app freezes", "technical_issue"),
    ("app freezing", "technical_issue"),
    ("application freezes", "technical_issue"),
    ("keeps freezing", "technical_issue"),
    ("frozen screen", "technical_issue"),
    ("not responding", "technical_issue"),
    ("app not responding", "technical_issue"),
    ("stuck on loading", "technical_issue"),
    ("loading forever", "technical_issue"),
    ("wont load", "technical_issue"),
    ("not loading", "technical_issue"),
    ("error message", "technical_issue"),
    ("getting error", "technical_issue"),
    ("error appears", "technical_issue"),
    ("error keeps showing", "technical_issue"),
    ("seeing an error", "technical_issue"),
    ("technical error", "technical_issue"),
    ("system error", "technical_issue"),
    ("bug in the app", "technical_issue"),
    ("found a bug", "technical_issue"),
    ("something is broken", "technical_issue"),
    ("not working properly", "technical_issue"),
    ("not working correctly", "technical_issue"),
    ("not working right", "technical_issue"),
    ("app not working", "technical_issue"),
    ("doesnt work", "technical_issue"),
    ("stopped working", "technical_issue"),
    ("suddenly stopped working", "technical_issue"),
    ("slow performance", "technical_issue"),
    ("very slow", "technical_issue"),
    ("running slow", "technical_issue"),
    ("laggy", "technical_issue"),
    ("lagging", "technical_issue"),
    ("app is slow", "technical_issue"),
    ("taking forever", "technical_issue"),
    ("not syncing", "technical_issue"),
    ("sync not working", "technical_issue"),
    ("sync failed", "technical_issue"),
    ("sync error", "technical_issue"),
    ("data not syncing", "technical_issue"),
    ("not synchronizing", "technical_issue"),
    ("connection error", "technical_issue"),
    ("connection failed", "technical_issue"),
    ("cant connect", "technical_issue"),
    ("cannot connect", "technical_issue"),
    ("unable to connect", "technical_issue"),
    ("no connection", "technical_issue"),
    ("lost connection", "technical_issue"),
    ("disconnected", "technical_issue"),
    ("keeps disconnecting", "technical_issue"),
    ("connection timeout", "technical_issue"),
    ("server error", "technical_issue"),
    ("server not responding", "technical_issue"),
    ("server down", "technical_issue"),
    ("server unavailable", "technical_issue"),
    ("service unavailable", "technical_issue"),
    ("500 error", "technical_issue"),
    ("404 error", "technical_issue"),
    ("network error", "technical_issue"),
    ("internet connection problem", "technical_issue"),
    ("offline mode not working", "technical_issue"),
    ("blank screen", "technical_issue"),
    ("white screen", "technical_issue"),
    ("black screen", "technical_issue"),
    ("nothing shows up", "technical_issue"),
    ("page not loading", "technical_issue"),
    ("page blank", "technical_issue"),
    ("buttons not working", "technical_issue"),
    ("cant click anything", "technical_issue"),
    ("interface not working", "technical_issue"),
    ("features not working", "technical_issue"),
    ("glitch in the system", "technical_issue"),
    ("glitchy", "technical_issue"),
    ("graphics issue", "technical_issue"),
    ("display problem", "technical_issue"),
    ("screen flickering", "technical_issue"),
    ("images not loading", "technical_issue"),
    ("images not showing", "technical_issue"),
    ("files not uploading", "technical_issue"),
    ("upload failed", "technical_issue"),
    ("upload error", "technical_issue"),
    ("cant upload files", "technical_issue"),
    ("download not working", "technical_issue"),
    ("cant download", "technical_issue"),
    ("download failed", "technical_issue"),
    ("download error", "technical_issue"),
    ("export not working", "technical_issue"),
    ("cant export data", "technical_issue"),
    ("export failed", "technical_issue"),
    ("import not working", "technical_issue"),
    ("cant import", "technical_issue"),
    ("data lost", "technical_issue"),
    ("lost my data", "technical_issue"),
    ("data disappeared", "technical_issue"),
    ("data missing", "technical_issue"),
    ("missing information", "technical_issue"),
    ("information missing", "technical_issue"),
    ("corrupted file", "technical_issue"),
    ("file corrupted", "technical_issue"),
    ("data corrupted", "technical_issue"),
    ("app wont open", "technical_issue"),
    ("cant open app", "technical_issue"),
    ("wont start", "technical_issue"),
    ("app wont start", "technical_issue"),
    ("startup error", "technical_issue"),
    ("initialization failed", "technical_issue"),
    ("installation failed", "technical_issue"),
    ("cant install", "technical_issue"),
    ("installation error", "technical_issue"),
    ("update failed", "technical_issue"),
    ("cant update", "technical_issue"),
    ("update not working", "technical_issue"),
    ("update error", "technical_issue"),
    ("notification not working", "technical_issue"),
    ("not getting notifications", "technical_issue"),
    ("notifications stopped", "technical_issue"),
    ("search not working", "technical_issue"),
    ("cant search", "technical_issue"),
    ("search broken", "technical_issue"),
    ("filter not working", "technical_issue"),
    ("sort not working", "technical_issue"),
    
    # ============================================================================
    # BILLING - Subscription, Payment, Refunds (120+ variations)
    # ============================================================================
    ("billing question", "billing"),
    ("billing issue", "billing"),
    ("billing problem", "billing"),
    ("billing help", "billing"),
    ("billing inquiry", "billing"),
    ("payment question", "billing"),
    ("payment issue", "billing"),
    ("payment problem", "billing"),
    ("payment help", "billing"),
    ("payment not working", "billing"),
    ("cant make payment", "billing"),
    ("payment failed", "billing"),
    ("payment error", "billing"),
    ("payment declined", "billing"),
    ("card declined", "billing"),
    ("credit card declined", "billing"),
    ("payment method declined", "billing"),
    ("subscription cost", "billing"),
    ("how much does it cost", "billing"),
    ("what is the price", "billing"),
    ("pricing information", "billing"),
    ("pricing question", "billing"),
    ("subscription price", "billing"),
    ("plan cost", "billing"),
    ("how much is subscription", "billing"),
    ("subscription fee", "billing"),
    ("monthly fee", "billing"),
    ("annual fee", "billing"),
    ("yearly cost", "billing"),
    ("cancel subscription", "billing"),
    ("cancel my subscription", "billing"),
    ("want to cancel", "billing"),
    ("how to cancel subscription", "billing"),
    ("stop subscription", "billing"),
    ("end subscription", "billing"),
    ("terminate subscription", "billing"),
    ("unsubscribe", "billing"),
    ("discontinue service", "billing"),
    ("refund request", "billing"),
    ("request a refund", "billing"),
    ("want a refund", "billing"),
    ("need a refund", "billing"),
    ("can i get refund", "billing"),
    ("refund please", "billing"),
    ("money back", "billing"),
    ("get my money back", "billing"),
    ("return my payment", "billing"),
    ("refund policy", "billing"),
    ("what is refund policy", "billing"),
    ("charged twice", "billing"),
    ("double charged", "billing"),
    ("duplicate charge", "billing"),
    ("charged multiple times", "billing"),
    ("wrong amount charged", "billing"),
    ("incorrect charge", "billing"),
    ("overcharged", "billing"),
    ("charged too much", "billing"),
    ("billing error on card", "billing"),
    ("unauthorized charge", "billing"),
    ("didnt authorize this charge", "billing"),
    ("charge i didnt make", "billing"),
    ("unknown charge", "billing"),
    ("upgrade plan", "billing"),
    ("upgrade subscription", "billing"),
    ("change plan", "billing"),
    ("switch plan", "billing"),
    ("downgrade plan", "billing"),
    ("downgrade subscription", "billing"),
    ("change subscription", "billing"),
    ("modify subscription", "billing"),
    ("different plan", "billing"),
    ("invoice", "billing"),
    ("need invoice", "billing"),
    ("send invoice", "billing"),
    ("invoice copy", "billing"),
    ("get invoice", "billing"),
    ("download invoice", "billing"),
    ("invoice not received", "billing"),
    ("didnt get invoice", "billing"),
    ("missing invoice", "billing"),
    ("receipt", "billing"),
    ("need receipt", "billing"),
    ("payment receipt", "billing"),
    ("proof of payment", "billing"),
    ("billing statement", "billing"),
    ("account statement", "billing"),
    ("payment history", "billing"),
    ("billing history", "billing"),
    ("transaction history", "billing"),
    ("view past payments", "billing"),
    ("past invoices", "billing"),
    ("update payment method", "billing"),
    ("change payment method", "billing"),
    ("update credit card", "billing"),
    ("change credit card", "billing"),
    ("add new card", "billing"),
    ("remove payment method", "billing"),
    ("delete card", "billing"),
    ("payment method expired", "billing"),
    ("card expired", "billing"),
    ("expired credit card", "billing"),
    ("update billing info", "billing"),
    ("change billing information", "billing"),
    ("billing address", "billing"),
    ("update billing address", "billing"),
    ("change billing address", "billing"),
    ("trial period", "billing"),
    ("free trial", "billing"),
    ("trial expired", "billing"),
    ("trial ending", "billing"),
    ("extend trial", "billing"),
    ("trial questions", "billing"),
    ("promo code", "billing"),
    ("discount code", "billing"),
    ("coupon code", "billing"),
    ("apply discount", "billing"),
    ("use promo code", "billing"),
    ("where to enter promo code", "billing"),
    ("student discount", "billing"),
    ("educational discount", "billing"),
    ("nonprofit discount", "billing"),
    
    # ============================================================================
    # FEATURE HELP - How to use features (100+ variations)
    # ============================================================================
    ("how to use", "feature_help"),
    ("how do i use", "feature_help"),
    ("how does it work", "feature_help"),
    ("how to", "feature_help"),
    ("help me use", "feature_help"),
    ("show me how", "feature_help"),
    ("explain how to", "feature_help"),
    ("tutorial", "feature_help"),
    ("guide", "feature_help"),
    ("instructions", "feature_help"),
    ("documentation", "feature_help"),
    ("user guide", "feature_help"),
    ("need help with feature", "feature_help"),
    ("feature help", "feature_help"),
    ("feature question", "feature_help"),
    ("feature not working", "feature_help"),
    ("cant find feature", "feature_help"),
    ("where is feature", "feature_help"),
    ("how to export", "feature_help"),
    ("how to export data", "feature_help"),
    ("export my data", "feature_help"),
    ("export information", "feature_help"),
    ("download my data", "feature_help"),
    ("download information", "feature_help"),
    ("get my data", "feature_help"),
    ("backup data", "feature_help"),
    ("how to backup", "feature_help"),
    ("create backup", "feature_help"),
    ("backup my information", "feature_help"),
    ("save my data", "feature_help"),
    ("how to share", "feature_help"),
    ("share with team", "feature_help"),
    ("share with others", "feature_help"),
    ("collaborate", "feature_help"),
    ("add team member", "feature_help"),
    ("invite user", "feature_help"),
    ("invite team", "feature_help"),
    ("team collaboration", "feature_help"),
    ("sharing permissions", "feature_help"),
    ("user permissions", "feature_help"),
    ("access control", "feature_help"),
    ("who can see my data", "feature_help"),
    ("how to import", "feature_help"),
    ("import data", "feature_help"),
    ("import file", "feature_help"),
    ("upload file", "feature_help"),
    ("upload data", "feature_help"),
    ("add data", "feature_help"),
    ("how to sync", "feature_help"),
    ("sync data", "feature_help"),
    ("synchronize", "feature_help"),
    ("sync between devices", "feature_help"),
    ("cross device sync", "feature_help"),
    ("integrate with", "feature_help"),
    ("integration", "feature_help"),
    ("connect to", "feature_help"),
    ("third party integration", "feature_help"),
    ("api access", "feature_help"),
    ("use api", "feature_help"),
    ("api documentation", "feature_help"),
    ("api key", "feature_help"),
    ("generate api key", "feature_help"),
    ("customize", "feature_help"),
    ("customization", "feature_help"),
    ("personalize", "feature_help"),
    ("change settings", "feature_help"),
    ("configure", "feature_help"),
    ("configuration", "feature_help"),
    ("settings", "feature_help"),
    ("preferences", "feature_help"),
    ("change preferences", "feature_help"),
    ("notification settings", "feature_help"),
    ("email notifications", "feature_help"),
    ("turn off notifications", "feature_help"),
    ("enable notifications", "feature_help"),
    ("privacy settings", "feature_help"),
    ("security settings", "feature_help"),
    ("two factor authentication", "feature_help"),
    ("enable 2fa", "feature_help"),
    ("setup 2fa", "feature_help"),
    ("security features", "feature_help"),
    ("mobile app", "feature_help"),
    ("mobile version", "feature_help"),
    ("app features", "feature_help"),
    ("desktop app", "feature_help"),
    ("keyboard shortcuts", "feature_help"),
    ("shortcuts", "feature_help"),
    ("quick actions", "feature_help"),
    ("automation", "feature_help"),
    ("automate tasks", "feature_help"),
    ("workflow automation", "feature_help"),
    ("reporting", "feature_help"),
    ("generate report", "feature_help"),
    ("create report", "feature_help"),
    ("analytics", "feature_help"),
    ("view analytics", "feature_help"),
    ("statistics", "feature_help"),
    
    # ============================================================================
    # ACCOUNT MANAGEMENT - Profile, Settings, Deletion (80+ variations)
    # ============================================================================
    ("delete account", "account_management"),
    ("delete my account", "account_management"),
    ("close account", "account_management"),
    ("remove account", "account_management"),
    ("deactivate account", "account_management"),
    ("cancel account", "account_management"),
    ("terminate account", "account_management"),
    ("account deletion", "account_management"),
    ("how to delete account", "account_management"),
    ("want to delete account", "account_management"),
    ("update profile", "account_management"),
    ("change profile", "account_management"),
    ("edit profile", "account_management"),
    ("profile information", "account_management"),
    ("update information", "account_management"),
    ("change email", "account_management"),
    ("update email", "account_management"),
    ("change email address", "account_management"),
    ("new email", "account_management"),
    ("change phone number", "account_management"),
    ("update phone", "account_management"),
    ("change name", "account_management"),
    ("update name", "account_management"),
    ("profile picture", "account_management"),
    ("change profile picture", "account_management"),
    ("upload photo", "account_management"),
    ("avatar", "account_management"),
    ("account settings", "account_management"),
    ("account preferences", "account_management"),
    ("manage account", "account_management"),
    ("account details", "account_management"),
    ("account information", "account_management"),
    ("view account", "account_management"),
    ("account status", "account_management"),
    ("account type", "account_management"),
    ("privacy", "account_management"),
    ("privacy policy", "account_management"),
    ("data privacy", "account_management"),
    ("who can see my data", "account_management"),
    ("data security", "account_management"),
    ("secure my account", "account_management"),
    ("account security", "account_management"),
    ("verify account", "account_management"),
    ("account verification", "account_management"),
    ("verify email", "account_management"),
    ("verify phone", "account_management"),
    ("verification", "account_management"),
    ("create new account", "account_management"),
    ("sign up", "account_management"),
    ("register", "account_management"),
    ("new user", "account_management"),
    ("account registration", "account_management"),
    ("multiple accounts", "account_management"),
    ("second account", "account_management"),
    ("switch accounts", "account_management"),
    ("change account", "account_management"),
    ("merge accounts", "account_management"),
    ("combine accounts", "account_management"),
    ("link accounts", "account_management"),
    ("username", "account_management"),
    ("change username", "account_management"),
    ("update username", "account_management"),
    ("display name", "account_management"),
    ("notification preferences", "account_management"),
    ("language", "account_management"),
    ("change language", "account_management"),
    ("timezone", "account_management"),
    ("time zone", "account_management"),
    ("change timezone", "account_management"),
    ("region settings", "account_management"),
    ("country", "account_management"),
    ("location settings", "account_management"),
    
    # ============================================================================
    # DATA CONCERNS - Export, Privacy, Security (60+ variations)
    # ============================================================================
    ("export all data", "data_export"),
    ("download all data", "data_export"),
    ("get all my data", "data_export"),
    ("data export", "data_export"),
    ("full data export", "data_export"),
    ("export everything", "data_export"),
    ("download everything", "data_export"),
    ("backup all data", "data_export"),
    ("copy of my data", "data_export"),
    ("data download", "data_export"),
    ("gdpr data request", "data_export"),
    ("gdpr export", "data_export"),
    ("data portability", "data_export"),
    ("transfer my data", "data_export"),
    ("move my data", "data_export"),
    ("migrate data", "data_export"),
    ("take my data with me", "data_export"),
    ("what data do you have", "data_export"),
    ("what information stored", "data_export"),
    ("what data collected", "data_export"),
    ("privacy concern", "data_export"),
    ("data privacy", "data_export"),
    ("who has access to my data", "data_export"),
    ("data access", "data_export"),
    ("data sharing", "data_export"),
    ("who can see my information", "data_export"),
    ("is my data secure", "data_export"),
    ("data security", "data_export"),
    ("security concern", "data_export"),
    ("protect my data", "data_export"),
    ("data protection", "data_export"),
    ("encryption", "data_export"),
    ("is data encrypted", "data_export"),
    ("data breach", "data_export"),
    ("security breach", "data_export"),
    ("compromised account", "data_export"),
    ("hacked account", "data_export"),
    ("suspicious activity", "data_export"),
    ("unauthorized access", "data_export"),
    ("someone accessed my account", "data_export"),
    ("delete all data", "data_export"),
    ("remove all data", "data_export"),
    ("clear all data", "data_export"),
    ("erase everything", "data_export"),
    ("wipe my data", "data_export"),
    ("right to be forgotten", "data_export"),
    ("gdpr deletion", "data_export"),
    
    # ============================================================================
    # GENERAL INQUIRY - Product info, availability (60+ variations)
    # ============================================================================
    ("product information", "general_inquiry"),
    ("tell me about product", "general_inquiry"),
    ("what is this", "general_inquiry"),
    ("what does it do", "general_inquiry"),
    ("product details", "general_inquiry"),
    ("product features", "general_inquiry"),
    ("what features", "general_inquiry"),
    ("capabilities", "general_inquiry"),
    ("what can it do", "general_inquiry"),
    ("functionality", "general_inquiry"),
    ("how does this work", "general_inquiry"),
    ("explain the product", "general_inquiry"),
    ("product overview", "general_inquiry"),
    ("available features", "general_inquiry"),
    ("feature list", "general_inquiry"),
    ("supported platforms", "general_inquiry"),
    ("what platforms", "general_inquiry"),
    ("compatibility", "general_inquiry"),
    ("system requirements", "general_inquiry"),
    ("requirements", "general_inquiry"),
    ("works on mobile", "general_inquiry"),
    ("mobile support", "general_inquiry"),
    ("ios app", "general_inquiry"),
    ("android app", "general_inquiry"),
    ("desktop version", "general_inquiry"),
    ("web version", "general_inquiry"),
    ("browser support", "general_inquiry"),
    ("supported browsers", "general_inquiry"),
    ("operating system", "general_inquiry"),
    ("windows support", "general_inquiry"),
    ("mac support", "general_inquiry"),
    ("linux support", "general_inquiry"),
    ("new features", "general_inquiry"),
    ("latest features", "general_inquiry"),
    ("recent updates", "general_inquiry"),
    ("what's new", "general_inquiry"),
    ("roadmap", "general_inquiry"),
    ("future features", "general_inquiry"),
    ("upcoming features", "general_inquiry"),
    ("planned features", "general_inquiry"),
    ("feature request", "general_inquiry"),
    ("suggest feature", "general_inquiry"),
    ("request feature", "general_inquiry"),
    ("add feature", "general_inquiry"),
    ("comparison", "general_inquiry"),
    ("compare plans", "general_inquiry"),
    ("difference between plans", "general_inquiry"),
    ("which plan", "general_inquiry"),
    ("plan comparison", "general_inquiry"),
    ("free vs paid", "general_inquiry"),
    ("trial vs full", "general_inquiry"),
    ("limits", "general_inquiry"),
    ("usage limits", "general_inquiry"),
    ("storage limit", "general_inquiry"),
    ("user limit", "general_inquiry"),
    ("file size limit", "general_inquiry"),
    
    # ============================================================================
    # FEEDBACK - Positive, Negative, Suggestions (50+ variations)
    # ============================================================================
    ("great service", "feedback_positive"),
    ("excellent", "feedback_positive"),
    ("amazing", "feedback_positive"),
    ("love it", "feedback_positive"),
    ("love this", "feedback_positive"),
    ("fantastic", "feedback_positive"),
    ("wonderful", "feedback_positive"),
    ("perfect", "feedback_positive"),
    ("works great", "feedback_positive"),
    ("really helpful", "feedback_positive"),
    ("very useful", "feedback_positive"),
    ("impressed", "feedback_positive"),
    ("exceeded expectations", "feedback_positive"),
    ("highly recommend", "feedback_positive"),
    ("best app", "feedback_positive"),
    ("best service", "feedback_positive"),
    ("thank you", "feedback_positive"),
    ("thanks", "feedback_positive"),
    ("appreciate it", "feedback_positive"),
    ("you guys are great", "feedback_positive"),
    ("awesome support", "feedback_positive"),
    ("quick response", "feedback_positive"),
    ("fast help", "feedback_positive"),
    ("problem solved", "feedback_positive"),
    ("issue resolved", "feedback_positive"),
    ("this is terrible", "feedback_negative"),
    ("worst app", "feedback_negative"),
    ("disappointed", "feedback_negative"),
    ("not satisfied", "feedback_negative"),
    ("unhappy", "feedback_negative"),
    ("frustrated", "feedback_negative"),
    ("waste of money", "feedback_negative"),
    ("waste of time", "feedback_negative"),
    ("doesnt work", "feedback_negative"),
    ("never works", "feedback_negative"),
    ("always broken", "feedback_negative"),
    ("constant problems", "feedback_negative"),
    ("too many bugs", "feedback_negative"),
    ("buggy", "feedback_negative"),
    ("unreliable", "feedback_negative"),
    ("not worth it", "feedback_negative"),
    ("regret subscribing", "feedback_negative"),
    ("want refund", "feedback_negative"),
    ("poor quality", "feedback_negative"),
    ("low quality", "feedback_negative"),
    ("bad experience", "feedback_negative"),
    ("horrible", "feedback_negative"),
    ("awful", "feedback_negative"),
    
    # ============================================================================
    # OUT OF SCOPE - Custom dev, partnerships, sales (40+ variations)
    # ============================================================================
    ("custom development", "out_of_scope"),
    ("custom solution", "out_of_scope"),
    ("build custom feature", "out_of_scope"),
    ("custom integration", "out_of_scope"),
    ("enterprise solution", "out_of_scope"),
    ("business partnership", "out_of_scope"),
    ("partner with you", "out_of_scope"),
    ("partnership opportunity", "out_of_scope"),
    ("collaborate on project", "out_of_scope"),
    ("investment opportunity", "out_of_scope"),
    ("invest in company", "out_of_scope"),
    ("funding", "out_of_scope"),
    ("reseller", "out_of_scope"),
    ("become reseller", "out_of_scope"),
    ("white label", "out_of_scope"),
    ("rebrand your product", "out_of_scope"),
    ("press inquiry", "out_of_scope"),
    ("media inquiry", "out_of_scope"),
    ("journalist", "out_of_scope"),
    ("interview request", "out_of_scope"),
    ("job opening", "out_of_scope"),
    ("career opportunity", "out_of_scope"),
    ("hiring", "out_of_scope"),
    ("apply for job", "out_of_scope"),
    ("work for you", "out_of_scope"),
    ("join team", "out_of_scope"),
    ("legal question", "out_of_scope"),
    ("legal issue", "out_of_scope"),
    ("lawyer", "out_of_scope"),
    ("terms of service question", "out_of_scope"),
    ("compliance", "out_of_scope"),
    ("regulatory", "out_of_scope"),
    ("speak to ceo", "out_of_scope"),
    ("talk to manager", "out_of_scope"),
    ("escalate", "out_of_scope"),
    ("complaint to management", "out_of_scope"),
    ("corporate office", "out_of_scope"),
    ("headquarters", "out_of_scope"),

    # =============================
# Added Edge Case Improvements
# =============================

("2fa not working", "account_access"),
("authentication problem", "account_access"),
("cant login to my account", "account_access"),

("i want a refund", "billing"),
("refund request", "billing"),
("subscription refund", "billing"),

("what are the plans", "billing"),
("pricing plans", "billing"),

("change password", "account_management"),
("enable 2fa", "account_management"),
("privacy settings", "account_management"),

("privacy policy", "data_export"),
("gdpr compliance", "data_export"),

("mobile app available", "general_inquiry"),
("do you have mobile app", "general_inquiry"),

("this sucks", "feedback_negative"),
("bad experience", "feedback_negative"),


]

# Additional augmentation patterns for more diversity
AUGMENTATION_PATTERNS = {
    "account_access": [
        "login troubles",
        "access issue",
        "getting in",
        "log in problem",
        "entry denied",
    ],
    "technical_issue": [
        "tech problem",
        "software issue",
        "system problem",
        "technical difficulty",
        "application error",
    ],
    "billing": [
        "money matter",
        "payment concern",
        "subscription matter",
        "financial question",
        "billing concern",
    ],
    "feature_help": [
        "feature question",
        "using the app",
        "learning how to",
        "need guidance",
        "instructions needed",
    ],
    
}
# ================================
# LABEL MERGING + ML FILTER
# ================================

MERGE_MAP = {
    "account_access": "account_support",
    "account_management": "account_support",
    "data_export": "data_privacy",
    "general_inquiry": "feature_help"
}

EXCLUDE_FROM_ML = {
    "greeting",
    "farewell",
    "feedback_positive",
    "feedback_negative"
}

UPDATED_TRAINING_DATA = []

for text, label in CORE_TRAINING_DATA:
    new_label = MERGE_MAP.get(label, label)

    if new_label not in EXCLUDE_FROM_ML:
        UPDATED_TRAINING_DATA.append((text, new_label))

